language: python
python:
        - "3.4"
#branches:
#        only: master
env:
        - TOXENV=py27
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=pypy
        - TOXENV=coverage
        - TOXENV=flake8
install:
        - travis_retry sudo apt-get update
        - travis_retry sudo apt-get install rsync
        - travis_retry pip install tox
script: tox -e $TOXENV
