language: python
python:
        - "3.4"
#branches:
#        only: master
env:
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=flake8
install:
        - travis_retry sudo apt-get update
        - travis_retry sudo apt-get install rsync
        - travis_retry pip install tox
script: tox -e $TOXENV
before_install:
        - pip install codecov
after_success:
        - codecov
